### ISSUE TITLE
Something goes wrong with CholBFGS

### ISSUE THREAD

**Issue by stepanzh** [vvpisarev/DescentMethods.jl#17]
After updating from 2833a489a1e9a23b8ef48cd696fa6b36f49d8fbe to  d06cab7872b6a208e02d47030586a14ccb9b7c3f `CubicEoS.vt_stability` procedure fails to run. It goes into negative unfeasible argument. The procedure uses `CholBFGS` as optimizer.

**Comment by vvpisarev** [comment]
In the last commit, I've inadvertently removed the overload for `step!` with `ConstrainStepSize` wrapper, so the step size constraint was ignored. Adding it back must fix the issue.
